spring:
  profile:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://localhost:3306/community
    #    username: root
    #    password: 419914
    url: jdbc:mysql://perillaleaves.cxvfbpskmkd3.ap-northeast-2.rds.amazonaws.com:3306/project
    username: admin
    password: 12341234
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
      show-sql: true
      format-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 10
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
server:
  address: 0.0.0.0
  port: 80
  servlet:
    session:
      timeout: 1800
      cookie:
        http-only: true
        same-site: none